<?php
Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
// Auth::routes(['register' => false]);
Route::post('userlogin','Auth\\LoginController@authenticate')->name('userlogin');
Route::group( ['prefix' => 'admin','middleware' => 'auth' ], function()
{
    Route::get('/', 'Admin\DashboardController@highlight');
    Route::get('/changepassword', 'Admin\UserController@changepassword');
    Route::post('/editpassword', 'Admin\UserController@editpassword');
    Route::get('/myprofile', 'Admin\UserController@myprofile');
    Route::post('/updateprofile', 'Admin\UserController@updateprofile');
    Route::get('/highlight', 'Admin\DashboardController@highlight');
    Route::get('/dashboard', 'Admin\DashboardController@dashboard');
    Route::get('/adsperformance', 'Admin\AdsperformanceController@index');
    Route::post('/adsperformance/indexjson', 'Admin\AdsperformanceController@indexjson');
    Route::get('/adsperformance/search-targetaudience-json', 'Admin\TargetaudienceController@searchjson');    
    Route::get('/adsperformance/search-channel-json', 'Admin\ChannelController@searchjson');    
    Route::get('/adsperformance/search-nprogramme-json', 'Admin\TvprogrammesearchController@searchnprogrammejson');    
    Route::get('/adsperformance/search-nlevel1-json', 'Admin\TvprogrammesearchController@searchnlevel1json');    
    Route::get('/adsperformance/search-nlevel2-json', 'Admin\TvprogrammesearchController@searchnlevel2json');    
    Route::get('/adsperformance/search-nadvertiser-json', 'Admin\CommercialsearchController@searchnadvertiserjson');    
    Route::get('/adsperformance/search-nproduct-json', 'Admin\CommercialsearchController@searchnproductjson');    
    Route::get('/adsperformance/search-nsector-json', 'Admin\CommercialsearchController@searchnsectorjson');    
    Route::get('/adsperformance/search-ncategory-json', 'Admin\CommercialsearchController@searchncategoryjson');    
    Route::get('/adsperformance/search-nadstype-json', 'Admin\AdstypesearchController@searchnadstypejson'); 
    Route::get('/adsperformance/search-ncopy-json', 'Admin\CommercialsearchController@searchncopyjson'); 
    Route::get('/tvads', 'Admin\VideoController@tvads');
    Route::post('/tvads/indexjson', 'Admin\VideoController@tvadsjson');
    Route::get('/tvprogramme', 'Admin\VideoController@tvprogramme');
    Route::post('/tvprogramme/indexjson', 'Admin\VideoController@tvprogrammejson');
    Route::get('/video/generatevideo', 'Admin\VideoController@generatevideo');
    Route::get('/video/logdownload', 'Admin\VideoController@logdownload');
    Route::get('/mktsummary', 'Admin\MarketingController@mktsummary');
    Route::get('/adexnett', 'Admin\MarketingController@adexnett');
    Route::post('/adexnett/indexjson', 'Admin\MarketingController@adexnettjson');
    Route::get('/spotmatching', 'Admin\MarketingController@spotmatching');
    Route::post('/spotmatching/indexjson', 'Admin\MarketingController@spotmatchingjson');
    /**/
    Route::get('/uploaddata/commercial', 'Admin\Uploaddata\CommercialController@index');
    Route::post('/uploaddata/commercial/upload', 'Admin\Uploaddata\CommercialController@upload');
    Route::post('/uploaddata/commercial/indexjson', 'Admin\Uploaddata\CommercialController@indexjson');
    Route::get('/uploaddata/commercial/destroymulti', 'Admin\Uploaddata\CommercialController@destroymulti');
    Route::get('/uploaddata/commercial/csvall', 'Admin\Uploaddata\CommercialController@csvall');
    Route::get('/uploaddata/commercialgrouped', 'Admin\Uploaddata\CommercialgroupedController@index');
    Route::post('/uploaddata/commercialgrouped/upload', 'Admin\Uploaddata\CommercialgroupedController@upload');
    Route::post('/uploaddata/commercialgrouped/indexjson', 'Admin\Uploaddata\CommercialgroupedController@indexjson');
    Route::get('/uploaddata/commercialgrouped/destroymulti', 'Admin\Uploaddata\CommercialgroupedController@destroymulti');
    Route::get('/uploaddata/commercialgrouped/csvall', 'Admin\Uploaddata\CommercialgroupedController@csvall');
    Route::get('/uploaddata/tvprogramme', 'Admin\Uploaddata\TvprogrammeController@index');
    Route::post('/uploaddata/tvprogramme/upload', 'Admin\Uploaddata\TvprogrammeController@upload');
    Route::post('/uploaddata/tvprogramme/indexjson', 'Admin\Uploaddata\TvprogrammeController@indexjson');
    Route::get('/uploaddata/tvprogramme/destroymulti', 'Admin\Uploaddata\TvprogrammeController@destroymulti');
    Route::get('/uploaddata/tvprogramme/csvall', 'Admin\Uploaddata\TvprogrammeController@csvall');
    Route::get('/uploaddata/adexnett', 'Admin\Uploaddata\AdexnettController@index');
    Route::post('/uploaddata/adexnett/upload', 'Admin\Uploaddata\AdexnettController@upload');
    Route::post('/uploaddata/adexnett/indexjson', 'Admin\Uploaddata\AdexnettController@indexjson');
    Route::get('/uploaddata/adexnett/destroymulti', 'Admin\Uploaddata\AdexnettController@destroymulti');
    Route::get('/uploaddata/adexnett/csvall', 'Admin\Uploaddata\AdexnettController@csvall');
    Route::get('/uploaddata/spotmatching', 'Admin\Uploaddata\SpotmatchingController@index');
    Route::post('/uploaddata/spotmatching/upload', 'Admin\Uploaddata\SpotmatchingController@upload');
    Route::post('/uploaddata/spotmatching/indexjson', 'Admin\Uploaddata\SpotmatchingController@indexjson');
    Route::get('/uploaddata/spotmatching/destroymulti', 'Admin\Uploaddata\SpotmatchingController@destroymulti');
    Route::get('/uploaddata/spotmatching/csvall', 'Admin\Uploaddata\SpotmatchingController@csvall');
    Route::get('/uploaddata/spotunpaired', 'Admin\Uploaddata\SpotunpairedController@index');
    Route::post('/uploaddata/spotunpaired/upload', 'Admin\Uploaddata\SpotunpairedController@upload');
    Route::post('/uploaddata/spotunpaired/indexjson', 'Admin\Uploaddata\SpotunpairedController@indexjson');
    Route::get('/uploaddata/spotunpaired/destroymulti', 'Admin\Uploaddata\SpotunpairedController@destroymulti');
    Route::get('/uploaddata/spotunpaired/csvall', 'Admin\Uploaddata\SpotunpairedController@csvall');
    /**/
    Route::get('/uploadsearch/commercial', 'Admin\Uploadsearch\CommercialController@index');
    Route::post('/uploadsearch/commercial/upload', 'Admin\Uploadsearch\CommercialController@upload');
    Route::post('/uploadsearch/commercial/indexjson', 'Admin\Uploadsearch\CommercialController@indexjson');
    Route::get('/uploadsearch/commercial/destroymulti', 'Admin\Uploadsearch\CommercialController@destroymulti');
    Route::get('/uploadsearch/commercial/csvall', 'Admin\Uploadsearch\CommercialController@csvall');
    Route::get('/uploadsearch/tvprogramme', 'Admin\Uploadsearch\TvprogrammeController@index');
    Route::post('/uploadsearch/tvprogramme/upload', 'Admin\Uploadsearch\TvprogrammeController@upload');
    Route::post('/uploadsearch/tvprogramme/indexjson', 'Admin\Uploadsearch\TvprogrammeController@indexjson');
    Route::get('/uploadsearch/tvprogramme/destroymulti', 'Admin\Uploadsearch\TvprogrammeController@destroymulti');
    Route::get('/uploadsearch/tvprogramme/csvall', 'Admin\Uploadsearch\TvprogrammeController@csvall');
    Route::get('/uploadsearch/adstype', 'Admin\Uploadsearch\AdstypeController@index');
    Route::post('/uploadsearch/adstype/upload', 'Admin\Uploadsearch\AdstypeController@upload');
    Route::post('/uploadsearch/adstype/indexjson', 'Admin\Uploadsearch\AdstypeController@indexjson');
    Route::get('/uploadsearch/adstype/destroymulti', 'Admin\Uploadsearch\AdstypeController@destroymulti');
    Route::get('/uploadsearch/adstype/csvall', 'Admin\Uploadsearch\AdstypeController@csvall');
    /**/
    Route::get('/spotpairing', 'Admin\VideoController@spotpairing');
    Route::get('/videodata', 'Admin\VideoController@videodata');
    Route::get('/videodata/indexjson', 'Admin\VideoController@videodatajson');
    Route::get('/videodata/create', 'Admin\VideoController@videodatacreate');
    Route::post('/videodatastore', 'Admin\VideoController@videodatastore');
    Route::get('/videodata/{a}/edit', 'Admin\VideoController@videodataedit');
    Route::patch('/videodataupdate/{a}', 'Admin\VideoController@videodataupdate');
    Route::get('/videodatadelete/{a}', 'Admin\VideoController@videodatadestroy');
    Route::post('/videodata/updateconfigs', 'Admin\VideoController@updateconfigs');
    Route::get('/targetaudience/indexjson','Admin\TargetaudienceController@indexjson');
    Route::get('/targetaudience/searchjson','Admin\TargetaudienceController@searchjson');
    Route::resource('/targetaudience', 'Admin\TargetaudienceController');
    Route::get('/channel/indexjson','Admin\ChannelController@indexjson');
    Route::get('/channel/searchjson','Admin\ChannelController@searchjson');
    Route::resource('/channel', 'Admin\ChannelController');
    Route::get('/user/indexjson','Admin\UserController@indexjson');
    Route::get('/user/csvall','Admin\UserController@csvall');
    Route::get('/user/destroymulti','Admin\UserController@destroymulti');
    Route::get('/user', 'Admin\UserController@index');
    Route::get('/user/create', 'Admin\UserController@create');
    Route::post('/user/store', 'Admin\UserController@store');
    Route::get('/user/{a}/edit', 'Admin\UserController@edit');
    Route::patch('/user/{a}/update', 'Admin\UserController@update');
    Route::get('/user/delete/{a}', 'Admin\UserController@destroy');
    Route::get('/role/privilegejson/{a}', 'Admin\RoleController@privilegejson');
    Route::patch('/role/privilegesave', 'Admin\RoleController@privilegesave');
    Route::get('/role', 'Admin\RoleController@edit');
    
});