<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Commercial extends Eloquent
{
    protected $guarded = ['id'];

    protected $casts = [
        'cost' => 'integer',
        'tvr01' => 'float',
        'tvr02' => 'float',
        'tvr03' => 'float',
        'tvr04' => 'float',
        'tvr05' => 'float',
        'tvr06' => 'float',
        'tvr07' => 'float',
        'tvr08' => 'float',
        'tvr09' => 'float',
        'tvr10' => 'float',
        'tvr11' => 'float',
        'tvr12'=>'float',
        'tvr13'=>'float',
        'tvr14'=>'float',
        'tvr15'=>'float',
        'tvr16'=>'float',
        'tvr17'=>'float',
        'tvr18'=>'float',
        'tvr19'=>'float',
        'tvr20'=>'float',
        'tvr21'=>'float',
        'tvr22'=>'float',
        'tvr23'=>'float',
        'tvr24'=>'float',
        'tvr25'=>'float',
        'tvr26'=>'float',
        'tvr27'=>'float',
        'tvr28'=>'float',
        'tvr29'=>'float',
        'tvr30'=>'float',
        'tvr31'=>'float',
        'tvr32'=>'float',
        'tvr33'=>'float',
        'tvr34'=>'float',
        'tvr35'=>'float',
        'tvr36'=>'float',
        'tvr37'=>'float',
        'tvr38'=>'float',
        'tvr39'=>'float',
        'tvr40'=>'float',
        'tvr41'=>'float',
        'tvr42'=>'float',
        'tvr43'=>'float',
        'tvr44'=>'float',
        'tvr45'=>'float',
        'tvr46'=>'float',
        'tvr47'=>'float',
        'tvr48'=>'float',
        'tvr49'=>'float',
        'tvr50'=>'float',
        'tvr51'=>'float',
        'tvr52'=>'float',
        'tvr53'=>'float',
        'tvr54'=>'float',
        'tvr55'=>'float',
        'tvr56'=>'float',
        'tvr57'=>'float',
        'tvr58'=>'float',
        'tvr59'=>'float',
        'tvr60'=>'float',
        'tvr61'=>'float',
        'tvr62'=>'float',
        'tvr63'=>'float',
        'tvr64'=>'float',
        'tvr65'=>'float',
        'tvr66'=>'float',
        'tvr67'=>'float',
        'tvr68'=>'float',
        'tvr69'=>'float',
        'tvr70'=>'float',
        'tvr71'=>'float',
        'tvr72'=>'float',
        'tvr73'=>'float',
        'tvr74'=>'float',
        'tvr75'=>'float',
        'tvr76'=>'float',
        'tvr77'=>'float',
        'tvr78'=>'float',
        'tvr79'=>'float',
        'tvr80'=>'float',
        'tvr81'=>'float',
        'tvr82'=>'float',
        'tvr83'=>'float',
        'tvr84'=>'float',
        'tvr85'=>'float',
        'tvr86'=>'float',
        'tvr87'=>'float',
        'tvr88'=>'float',
        'tvr89'=>'float',
        'tvr90'=>'float',
        'tvr91'=>'float',
        'tvr92'=>'float',
        'tvr93'=>'float',
        'tvr94'=>'float',
        'tvr95'=>'float',
        'tvr96'=>'float',
        'tvr97'=>'float',
        'tvr98'=>'float',
        'tvr99'=>'float',
        'tvr100'=>'float',
    ];

    public function setAttribute($key, $value)
    {
    if ($this->hasCast($key)) {
    $value = $this->castAttribute($key, $value);
    }
    return parent::setAttribute($key, $value);
    }
}